### ISSUE TITLE
pamu2fcfg depends on libjson-c.so.2 that is no longer shipped with ubuntu

### ISSUE THREAD

**Issue by larlin** [Yubico/pam-u2f#45] opened 2016-11-20 12:38 UTC
When updating from ubuntu 16.04 to 16.10 u2f with yubikey u2fstopped working.

After a bit of looking around I discovered that pamu2fcfg doesn't work either and fails with:

paumu2fcfg: error while loading shared libraries: libjson-c.so.2: cannot open shared object file: No such file or directory

Looking around I find that ubuntu from version 16.10 no longer ships libjson-c.so.2 instead they ship libjson-c.so.3.

So I suspect that libpam-u2f also depends on libjson and that is why it fails, but I have no evidence of that.

**Comment by a-dma** [comment] 2016-11-21 08:55
I'm using 16.10 myself and I have no problems with either the module itself or pamu2fcfg.

Have your recently upgrade the library? Have you tried running `ldconfig`? What is the output of `ldd pamu2fcfg`?

**Comment by larlin** [comment] 2016-11-21 16:50
I tried running ldconfig on the pamu2fcfg, on the dir that contains libjson-c.so.3. Any other way that it should be used? Haven't needed to use it before so don't know how it is normally applied.

I guess the library was update as part of the system upgrade I haven't done anything more.

Here is the output from ldd:
`ldd /usr/local/bin/pamu2fcfg 
	linux-vdso.so.1 =>  (0x00007ffe837f0000)
	libu2f-host.so.0 => /usr/local/lib/libu2f-host.so.0 (0x00007f8500e6f000)
	libu2f-server.so.0 => /usr/local/lib/libu2f-server.so.0 (0x00007f8500c67000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f85008a0000)
	libhidapi-hidraw.so.0 => /usr/lib/x86_64-linux-gnu/libhidapi-hidraw.so.0 (0x00007f850069c000)
	libjson-c.so.2 => not found
	libjson-c.so.2 => not found
	libssl.so.1.0.0 => /lib/x86_64-linux-gnu/libssl.so.1.0.0 (0x00007f8500431000)
	libcrypto.so.1.0.0 => /lib/x86_64-linux-gnu/libcrypto.so.1.0.0 (0x00007f84fffed000)
	/lib64/ld-linux-x86-64.so.2 (0x000055e781fc3000)
	libudev.so.1 => /lib/x86_64-linux-gnu/libudev.so.1 (0x00007f84fffcc000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f84ffdc8000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f84ffbc0000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f84ff9a0000)
`

**Comment by a-dma** [comment] 2016-11-22 08:26
oh have _upgraded_ from 16.04 to 16.10...

try running `sudo apt-get dist-upgrade`, if that doesn't help try reinstalling pamu2fcfg `sudo apt-get --reinstall pamu2fcfg`

**Comment by larlin** [comment] 2016-11-22 08:40
Will do, I did try complete removal and install from Synaptic that didn't do any difference. But will try tonight when I have access to the machine again.

**Comment by a-dma** [comment] 2016-11-22 09:06
also since the binary is located in `/usr/local`, have you built the tool yourself? Is that what you're running? In that case you might want to rebuild to have it link against the updated version of the library.

**Comment by larlin** [comment] 2016-11-22 09:33
Doh! You are probably right I forgot that I had to build it my self when I started using u2f. Sorry for the time wasted on this. Then I probably only need to uninstall the version I built and then it will use the version from the package manager. Thank you so much for the help!

**Comment by a-dma** [comment] 2016-11-22 09:34
No worries.

I'm closing this, feel free to reopen if the problem isn't fixed.

**Closed by a-dma** 2016-11-22 09:34 UTC
