### ISSUE TITLE
Always getting "error: (-2) Error in JSON handling"

### ISSUE THREAD

**Issue by francescortiz** [Yubico/pam-u2f#5] opened 2015-01-17 10:35 UTC
I have this key:
http://www.amazon.es/dp/B00OGPO3ZS/ref=sr_ph?ie=UTF8&qid=1421490850&sr=1&keywords=u2f

I get the same whatever I do. This is the output for "pamu2fcfg -n -d"

```
USB send: 00ffffffff8600080807060504030201000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
USB write returned 65
USB read rc read 64
USB recv: 51e9e73083027a05040102007cba6404597848cd59d42045e38b74c263d2dccf40d34e152864066773a845a30c997d85fedcf46eaef6f958469d370d795cf8d7
No U2F device available, please insert one now, you have 15 secondsUSB send: 00ffffffff8600080807060504030201000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
USB write returned 65
USB read rc read 64
USB recv: 51e9e73000788f8ce179b7589acb40298fa9a6cccf7daaf190be6f850b4071d7cab201c676353f4ced2b938ffecf9c9e275be167fcaba8325c5eaf5f6f3ee715
No U2F device available, please insert one now, you have 14 secondsUSB send: 00ffffffff8600080807060504030201000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
USB write returned 65
USB read rc read 64
USB recv: ffffffff860011080706050403020126a4583b020106070000000000000000000000000000000000000000000000000000000000000000000000000000000000
device /dev/hidraw2 discovered as 'Plug-up'
  version (Interface, Major, Minor, Build): 2, 1, 6, 0  capFlags: 0

Device found!
JSON: { "challenge": "G3-SIaOxt2KuE_T7Jv0xiP0XP-J-dIKLBPtUuPxCrGg", "version": "U2F_V2", "appId": "pam:\/\/turbi" }
JSON challenge URL-B64: G3-SIaOxt2KuE_T7Jv0xiP0XP-J-dIKLBPtUuPxCrGg
client data: { "challenge": "G3-SIaOxt2KuE_T7Jv0xiP0XP-J-dIKLBPtUuPxCrGg", "origin": "pam:\/\/turbi", "typ": "navigator.id.finishEnrollment" }
JSON: { "challenge": "G3-SIaOxt2KuE_T7Jv0xiP0XP-J-dIKLBPtUuPxCrGg", "version": "U2F_V2", "appId": "pam:\/\/turbi" }
JSON app_id pam://turbi
USB send: 0026a4583b830047000103000000403ac910592dee9d0bf269752b99279213130e7c42ffd6fea8397939f1a17df9fe036fe62a55eff8a72006dcc696d46289b3
USB write returned 65
USB send: 0026a4583b006e37d295e4d257c3cbfce3dc85ce0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
USB write returned 65
USB read rc read 64
USB recv: ffffffff8600110807060504030201b37d2bc0020106070000000000000000000000000000000000000000000000000000000000000000000000000000000000
USB rc -2
error: (-2) Error in JSON handling
```

In chrome the key works properly.

How can I fix the problem?

Thank you

**Comment by a-dma** [comment] 2015-01-19 13:48
This seems to be a problem of libu2f-host and the plug-up key. We are looking into it.

**Comment by a-dma** [comment] 2015-01-20 14:54
We have added a timeout to libu2f-host to compensate for the fact that the plug-up key is a fair bit slower. It solves the problem for me with pam-u2f.

I'm closing this. Please feel free to reopen if the issue is still there.

A.

**Closed by a-dma** 2015-01-20 14:54 UTC

**Comment by frasty** [comment] 2015-01-20 18:14
I have the same key of the op. I do not run into timeouts anymore but it seems that the process get stuck in an endless loop:

<addr>$pamu2fcfg -n -d
USB send: 00b65267a683004700010300000040b2d5876aff2722335a96a7fff9cfd03d794f998f8602f1e4ab42d69f2f3e6406fbfb7ae7ced563e13b12a5967fb71a3144
USB write returned 65
USB send: 00b65267a600bf068665957acc230c1b9867e3d10000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
USB write returned 65
USB read rc read 64
USB recv: b65267a6830002698500000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
USB data (len 2): 6985
USB send: 00b65267a683004700010300000040b2d5876aff2722335a96a7fff9cfd03d794f998f8602f1e4ab42d69f2f3e6406fbfb7ae7ced563e13b12a5967fb71a3144
USB write returned 65
USB send: 00b65267a600bf068665957acc230c1b9867e3d10000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
USB write returned 65
USB read rc read 64
USB recv: b65267a6830002698500000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
USB data (len 2): 6985
USB send: 00b65267a683004700010300000040b2d5876aff2722335a96a7fff9cfd03d794f998f8602f1e4ab42d69f2f3e6406fbfb7ae7ced563e13b12a5967fb71a3144
USB write returned 65
USB send: 00b65267a600bf068665957acc230c1b9867e3d10000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
USB write returned 65
USB read rc read 64
USB recv: b65267a6830002698500000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
USB data (len 2): 6985
.....
</addr>

**Comment by a-dma** [comment] 2015-01-21 08:45
That looks to me like the key is not sending out any information, waiting for user presence.
Since the touch event on this device is performed only when the key is plugged in, try to disconnect the key, run pamu2fcfg and wait for it to prompt for a key insertion. At that point do plug in your key. It works relialby for me in this way.
Furthermore, I don't see the timeout messages in your debug printout. Have you just stripped them out? Are you sure you are using the latest version of libu2f-host (0.0.4)? At this moment this version is only available through github.

**Comment by francescortiz** [comment] 2015-01-21 09:08
I have tested the git version. It works, just once. For further uses I have to unplug it and plug it again. Chrome has this behavior too.

Once I have successfully used the key once, I get this:

```
~/.yubico/ pamu2fcfg -ufranki -d
USB send: 00ffffffff8600080807060504030201000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
USB write returned 65
now trying with timeout 2
now trying with timeout 4
USB read rc read 64
USB recv: ffffffff8600110807060504030201b0113bd4020106070000000000000000000000000000000000000000000000000000000000000000000000000000000000
device /dev/hidraw2 discovered as 'Plug-up'
  version (Interface, Major, Minor, Build): 2, 1, 6, 0  capFlags: 0
JSON: { "challenge": "l8GTmWLbufapCAFcVFFcQhukPzBHaYkd7OgIlMqPIV0", "version": "U2F_V2", "appId": "pam:\/\/turbi" }
JSON challenge URL-B64: l8GTmWLbufapCAFcVFFcQhukPzBHaYkd7OgIlMqPIV0
client data: { "challenge": "l8GTmWLbufapCAFcVFFcQhukPzBHaYkd7OgIlMqPIV0", "origin": "pam:\/\/turbi", "typ": "navigator.id.finishEnrollment" }
JSON: { "challenge": "l8GTmWLbufapCAFcVFFcQhukPzBHaYkd7OgIlMqPIV0", "version": "U2F_V2", "appId": "pam:\/\/turbi" }
JSON app_id pam://turbi
USB send: 00b0113bd48300470001030000004043a5e908ce3d0c82dbea2d7150f81f47b4ec7b47957c2f9aefbf9678dec86fe4036fe62a55eff8a72006dcc696d46289b3
USB write returned 65
USB send: 00b0113bd4006e37d295e4d257c3cbfce3dc85ce0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
USB write returned 65
now trying with timeout 2
now trying with timeout 4
USB read rc read 64
USB recv: b0113bd4830002698500000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
USB data (len 2): 6985
USB send: 00b0113bd48300470001030000004043a5e908ce3d0c82dbea2d7150f81f47b4ec7b47957c2f9aefbf9678dec86fe4036fe62a55eff8a72006dcc696d46289b3
USB write returned 65
USB send: 00b0113bd4006e37d295e4d257c3cbfce3dc85ce0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
USB write returned 65
now trying with timeout 2
now trying with timeout 4
USB read rc read 64
USB recv: b0113bd4830002698500000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
USB data (len 2): 6985
USB send: 00b0113bd48300470001030000004043a5e908ce3d0c82dbea2d7150f81f47b4ec7b47957c2f9aefbf9678dec86fe4036fe62a55eff8a72006dcc696d46289b3
USB write returned 65
USB send: 00b0113bd4006e37d295e4d257c3cbfce3dc85ce0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
USB write returned 65
now trying with timeout 2
now trying with timeout 4
USB read rc read 64
USB recv: b0113bd4830002698500000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
USB data (len 2): 6985
USB send: 00b0113bd48300470001030000004043a5e908ce3d0c82dbea2d7150f81f47b4ec7b47957c2f9aefbf9678dec86fe4036fe62a55eff8a72006dcc696d46289b3
USB write returned 65
USB send: 00b0113bd4006e37d295e4d257c3cbfce3dc85ce0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
USB write returned 65
now trying with timeout 2
now trying with timeout 4
...
```
And stays in this loop forever.

It would be great to be able to keep reusing the key without reinserting it, but I don't know how to debug the communications with the key to see what's going on.

Anyway, if I unplug the key then it fails to authenticate. If the key has to be reinserted it would be good if it prompted for the key again once it is reinserted instead of failing to authenticate right away. I see this as a minor issue because it is pretty easy to unplug the key right after each use.

**Comment by francescortiz** [comment] 2015-01-21 09:27
Well, if the key is not inserted it fails to authenticate without prompting for the key. So the usage is to keep the key always plugged, and reinsert it after each use. The problem I see here is that there is no way to know when the key has been used.

**Comment by a-dma** [comment] 2015-01-21 09:29
I'm afraid this is the intended behaviour of the key you have.
The only way to trigger the touch operation with your device is by plugging it in.

I also believe that (according to the U2F protocol) an authentication failure is the correct response in this case.

I would like to avoid introducing device-specific fixes. However, if you have a generic enough solution in mind, pull requests are more than welcome ;)

**Comment by francescortiz** [comment] 2015-01-21 09:39
Thank you. I am contacting the manufacturer of the key to see what they have to say about this. In case they point to possible solution I will create a pull request. If it has any device specific features I will look for a solution based on settings or configuration files, since this would keep the code generic. Would this be enough?
