### ISSUE TITLE
Entries order in u2f_keys + feature request

### ISSUE THREAD

**Issue by perceival** [Yubico/pam-u2f#273] opened 2022-08-05 06:23 UTC
I have an impression having version 4 key (without PIN support) listed before PIN enabled key in u2f_keys file is causing authentication with PIN required to fail for those keys after key version 4. More explanation in attached files.
[u2f_keys.txt](https://github.com/Yubico/pam-u2f/files/9265903/u2f_keys.txt)
[password-auth.txt](https://github.com/Yubico/pam-u2f/files/9265918/password-auth.txt)

Regarding feature request I would like to suggest in addition to pinverification=1 option to have available 2ndfactor option. It would require either PIN (in case of Yubikey 5) or fingerprint in case of Yubikey BIO.

**Comment by martelletto** [comment] 2022-08-05 08:47
Thank you for the detailed bug report. I am unable to reproduce the problem with pam_u2f.so built off the main branch. Could it be that the second YubiKey 5 has no PIN set? To rule out such scenario, could you share the module's debug output and the output of `fido2-token -I` on each key?

Regarding the feature request, I believe it makes sense. I will forward it to my colleagues, one of who will get back to you.

**Comment by perceival** [comment] 2022-08-06 03:02
You are right. I must have messed up with u2f_keys file. Not able to reproduce. Thanks!

**Comment by LDVG** [comment] 2022-11-10 07:37
Hi @perceival,

Thank you for the feature request. To get a better grasp of your current limitations, is it possible that it could be implemented using the PAM configuration stack or am I missing something? A minimal example below:

```shell
# First attempt built-in UV (fingerprint in the case of the YubiKey Bio).
auth sufficient pam_u2f.so cue userverification=1
# If above fails or built-in UV is not available, fall back to PIN.
auth sufficient pam_u2f.so cue pinverification=1
```

**Comment by LDVG** [comment] 2023-11-03 09:55
Closing this, please reopen if the above solution is insufficient.

**Closed by LDVG** 2023-11-03 09:55 UTC
